INSERT INTO categories ("name", "status", "unit") VALUES ('Mleko', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kefir', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Jogurt', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ser', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Twaróg', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Masło', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Śmietana', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Jaja', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Mąka pszenna', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Mąka żytnia', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Mąka kukurydziana', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Cukier biały', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Cukier trzcinowy', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Miód', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Drożdże', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Proszek do pieczenia', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Soda oczyszczona', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sól', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Pieprz', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Papryka', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Cynamon', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Gałka muszkatołowa', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Imbir', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kardamon', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kolendra', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kminek', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kurkuma', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Chili', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Bazylia', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Oregano', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Tymianek', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Rozmaryn', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Pietruszka', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Koperek', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kolendra (liście)', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Czarnuszka', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Makaron', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ryż', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kasza gryczana', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kasza jaglana', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kasza kuskus', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Soczewica czerwona', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ciecierzyca', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Fasola czerwona', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Groch', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kukurydza', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Marchew', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ziemniaki', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Pomidory', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ogórki', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Papryka czerwona', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Cebula', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Czosnek', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Por', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Seler', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Pietruszka (korzeń)', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Szpinak', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sałata', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kapusta', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Brokuły', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kalafior', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Brukselka', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Buraki', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Cukinia', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Bakłażan', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Dynia', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Jabłka', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Gruszki', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Śliwki', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Truskawki', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Maliny', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Jagody', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Borówki', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Banany', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Pomarańcze', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Mandarynki', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Cytryny', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Limonki', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Mango', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ananas', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kokos', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Awokado', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Brzoskwinie', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Nektarynki', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Morele', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Granaty', 'Confirmed', 'amount');
INSERT INTO categories ("name", "status", "unit") VALUES ('Winogrona', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Arbuz', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Melon', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Krewetki', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Łosoś', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Tuńczyk', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Dorsz', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Pstrąg', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Makrela', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Mintaj', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Panga', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Węgorz', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Karp', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kurczak', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Indyk', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kaczka', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Gęś', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Wołowina', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Wieprzowina', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Jagnięcina', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Baranina', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sarnina', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Dziczyzna', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Słonina', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Boczek', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kiełbasa', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Salami', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Szynka', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Parmezan', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Cheddar', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Gouda', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Mozzarella', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Feta', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ricotta', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Mascarpone', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Camembert', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Gorgonzola', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Brie', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Tofu', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Tempeh', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Seitan', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Nori', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Wasabi', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Imbir marynowany', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Soja', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sos sojowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Miso', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sos rybny', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sos ostrygowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sos hoisin', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ocet ryżowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kumin', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Curry', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Czosnek granulowany', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Papryka wędzona', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Papryka ostra', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Chili w proszku', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Płatki drożdżowe', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Pesto', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Pasta tahini', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Pasta sezamowa', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Hummus', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Nutella', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Dżem', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Konfitura', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Marmolada', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sok pomarańczowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sok jabłkowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sok winogronowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sok ananasowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sok grejpfrutowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sok marchwiowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Herbata', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kawa', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Kakao', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Gorzka czekolada', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Mleczna czekolada', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Biała czekolada', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Baton czekoladowy', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ciastka', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ciasto francuskie', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ciasto kruche', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ciasto drożdżowe', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ciasto biszkoptowe', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Bita śmietana', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Lody waniliowe', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Lody czekoladowe', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Lody truskawkowe', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Lody pistacjowe', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sorbet', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Keczup', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Musztarda', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Majonez', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Chrzan', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sos barbecue', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Olej rzepakowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Oliwa z oliwek', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Olej kokosowy', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Masło klarowane', 'Confirmed', 'g');
INSERT INTO categories ("name", "status", "unit") VALUES ('Olej sezamowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Olej arachidowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Olej słonecznikowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ocet balsamiczny', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ocet jabłkowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Ocet winny', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sos Worcester', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Sos Tabasco', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Bulion wołowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Bulion drobiowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Bulion warzywny', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Bulion grzybowy', 'Confirmed', 'ml');
INSERT INTO categories ("name", "status", "unit") VALUES ('Rosół', 'Confirmed', 'ml');

INSERT INTO food_categories ("name", "description") VALUES ('Wege', 'Potrawy bezmięsne i wegańskie.');
INSERT INTO food_categories ("name", "description") VALUES ('Meksykańska', 'Dania inspirowane kuchnią Meksyku.');
INSERT INTO food_categories ("name", "description") VALUES ('Fit', 'Zdrowe, niskokaloryczne potrawy.');
INSERT INTO food_categories ("name", "description") VALUES ('Włoska', 'Tradycyjne dania włoskie.');
INSERT INTO food_categories ("name", "description") VALUES ('Francuska', 'Delikatne i wyszukane dania kuchni francuskiej.');
INSERT INTO food_categories ("name", "description") VALUES ('Japońska', 'Dania inspirowane kuchnią Japonii.');
INSERT INTO food_categories ("name", "description") VALUES ('Chińska', 'Dania inspirowane kuchnią Chin.');
INSERT INTO food_categories ("name", "description") VALUES ('Indyjska', 'Dania pełne aromatycznych przypraw.');
INSERT INTO food_categories ("name", "description") VALUES ('Tajska', 'Dania kuchni tajskiej, pełne smaków i aromatów.');
INSERT INTO food_categories ("name", "description") VALUES ('Grecka', 'Tradycyjne dania kuchni greckiej.');
INSERT INTO food_categories ("name", "description") VALUES ('Polska', 'Tradycyjne polskie potrawy.');
INSERT INTO food_categories ("name", "description") VALUES ('Hiszpańska', 'Tradycyjne dania kuchni hiszpańskiej.');
INSERT INTO food_categories ("name", "description") VALUES ('Amerykańska', 'Klasyczne dania kuchni amerykańskiej.');
INSERT INTO food_categories ("name", "description") VALUES ('Turecka', 'Dania inspirowane kuchnią turecką.');
INSERT INTO food_categories ("name", "description") VALUES ('Wegańska', 'Potrawy bez produktów pochodzenia zwierzęcego.');
INSERT INTO food_categories ("name", "description") VALUES ('Bezglutenowa', 'Dania bez zawartości glutenu.');
INSERT INTO food_categories ("name", "description") VALUES ('Śródziemnomorska', 'Dania inspirowane kuchnią śródziemnomorską.');
INSERT INTO food_categories ("name", "description") VALUES ('Węgierska', 'Tradycyjne dania kuchni węgierskiej.');
INSERT INTO food_categories ("name", "description") VALUES ('Niemiecka', 'Tradycyjne dania kuchni niemieckiej.');
INSERT INTO food_categories ("name", "description") VALUES ('Rosyjska', 'Tradycyjne dania kuchni rosyjskiej.');
INSERT INTO food_categories ("name", "description") VALUES ('Angielska', 'Tradycyjne dania kuchni angielskiej.');
INSERT INTO food_categories ("name", "description") VALUES ('Brazylijska', 'Dania inspirowane kuchnią Brazylii.');
INSERT INTO food_categories ("name", "description") VALUES ('Karaibska', 'Dania inspirowane kuchnią Karaibów.');
INSERT INTO food_categories ("name", "description") VALUES ('Koreańska', 'Dania inspirowane kuchnią Korei.');
INSERT INTO food_categories ("name", "description") VALUES ('Wietnamska', 'Dania inspirowane kuchnią Wietnamu.');
INSERT INTO food_categories ("name", "description") VALUES ('Afrykańska', 'Dania inspirowane kuchnią Afryki.');
INSERT INTO food_categories ("name", "description") VALUES ('Australijska', 'Dania inspirowane kuchnią Australii.');
INSERT INTO food_categories ("name", "description") VALUES ('Kanadyjska', 'Dania inspirowane kuchnią Kanady.');
INSERT INTO food_categories ("name", "description") VALUES ('Śląska', 'Tradycyjne dania kuchni śląskiej.');
INSERT INTO food_categories ("name", "description") VALUES ('Galicyjska', 'Tradycyjne dania kuchni galicyjskiej.');
INSERT INTO food_categories ("name", "description") VALUES ('Litewska', 'Tradycyjne dania kuchni litewskiej.');
INSERT INTO food_categories ("name", "description") VALUES ('Żydowska', 'Tradycyjne dania kuchni żydowskiej.');
INSERT INTO food_categories ("name", "description") VALUES ('Arabska', 'Dania inspirowane kuchnią arabską.');
INSERT INTO food_categories ("name", "description") VALUES ('Marokańska', 'Dania inspirowane kuchnią Maroka.');
INSERT INTO food_categories ("name", "description") VALUES ('Cajun', 'Tradycyjne dania kuchni Cajun.');
INSERT INTO food_categories ("name", "description") VALUES ('Peruwiańska', 'Dania inspirowane kuchnią Peru.');
INSERT INTO food_categories ("name", "description") VALUES ('Fusion', 'Połączenie różnych stylów kuchni.');
INSERT INTO food_categories ("name", "description") VALUES ('Fast food', 'Szybkie dania na wynos.');
INSERT INTO food_categories ("name", "description") VALUES ('Slow food', 'Potrawy przygotowywane tradycyjnymi metodami.');
INSERT INTO food_categories ("name", "description") VALUES ('Organiczna', 'Potrawy przygotowane z ekologicznych składników.');
INSERT INTO food_categories ("name", "description") VALUES ('Paleo', 'Potrawy zgodne z dietą paleolityczną.');
INSERT INTO food_categories ("name", "description") VALUES ('Ketogeniczna', 'Potrawy zgodne z dietą ketogeniczną.');
INSERT INTO food_categories ("name", "description") VALUES ('Makrobiotyczna', 'Potrawy zgodne z zasadami makrobiotyki.');
INSERT INTO food_categories ("name", "description") VALUES ('Raw food', 'Surowe potrawy nieprzetworzone termicznie.');
INSERT INTO food_categories ("name", "description") VALUES ('Dietetyczna', 'Potrawy niskokaloryczne i zdrowe.');
INSERT INTO food_categories ("name", "description") VALUES ('Wegetariańska', 'Potrawy bezmięsne.');
INSERT INTO food_categories ("name", "description") VALUES ('Flexitariańska', 'Potrawy głównie roślinne, ale z dodatkiem mięsa.');
INSERT INTO food_categories ("name", "description") VALUES ('Wegańska', 'Potrawy bez produktów pochodzenia zwierzęcego.');
