-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.barcodes
(
    key character varying COLLATE pg_catalog."default" NOT NULL,
    product_id integer,
    CONSTRAINT "Barcode_pkey" PRIMARY KEY (key)
);

ALTER TABLE IF EXISTS public.barcodes
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.products
(
    "Id" serial NOT NULL,
    description character varying COLLATE pg_catalog."default",
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Products_pkey" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.products_categories
(
    product_id integer NOT NULL,
    category_id integer NOT NULL,
    PRIMARY KEY (product_id, category_id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id serial NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.barcodes
    ADD CONSTRAINT "Barcode_ProductId_fkey" FOREIGN KEY (product_id)
    REFERENCES public.products ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products_categories
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products_categories
    ADD FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
